name: hyper_thread_downloader
description: A Hyper Thread Downloader work with Dio packages.
version: 1.0.4+2
repository: https://github.com/769755893/hyper_thread_downloader

environment:
  sdk: ^2.18.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
